# Generated by Django 6.0.3 on 2026-04-06 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tutorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=20)),
                ('course_prefix', models.CharField(max_length=10)),
                ('course_number', models.CharField(max_length=10)),
                ('course_key', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('matched', 'Matched'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='searching', max_length=20)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
