# Generated by Django 6.0.3 on 2026-04-06 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sessionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='matched_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_sessions', to='api.tutorprofile'),
        ),
    ]
