# Generated by Django 6.0.3 on 2026-04-06 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sessionrequest_matched_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('in_person', 'In Person')], default='remote', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='matched_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_session_requests', to='api.tutorprofile'),
        ),
    ]
