# Generated by Codex on 2026-04-23

import json

import django.db.models.deletion
from django.db import migrations, models


COMMON_UNIVERSITIES = {
    "FAU": "Florida Atlantic University",
    "UF": "University of Florida",
    "UCF": "University of Central Florida",
}


def normalize_university_code(value):
    text = str(value or "").strip()
    compact = "".join(char for char in text.upper() if char.isalnum())
    if not compact:
        return "UNKNOWN"
    if len(compact) <= 10:
        return compact

    words = "".join(char if char.isalnum() else " " for char in text).split()
    initials = "".join(word[0] for word in words).upper()
    if 1 < len(initials) <= 10:
        return initials

    return compact[:10]


def clean_course_prefix(value):
    return str(value or "").upper().strip()[:10] or "GEN"


def clean_course_number(value):
    return str(value or "").strip()[:10] or "0000"


def split_course_code(value):
    compact = "".join(str(value or "").upper().split())
    prefix_chars = []
    number_chars = []
    found_number = False

    for char in compact:
        if not found_number and char.isalpha():
            prefix_chars.append(char)
        else:
            found_number = True
            number_chars.append(char)

    return clean_course_prefix("".join(prefix_chars)), clean_course_number("".join(number_chars))


def get_or_create_university(University, value, name=None):
    code = normalize_university_code(value)
    display_name = str(name or value or code).strip() or code
    university, _ = University.objects.get_or_create(
        code=code,
        defaults={"name": display_name},
    )
    return university


def get_or_create_course(Course, University, university_value, prefix, number):
    university = get_or_create_university(University, university_value)
    course, _ = Course.objects.get_or_create(
        university=university,
        prefix=clean_course_prefix(prefix),
        number=clean_course_number(number),
    )
    return course


def parse_legacy_courses(value):
    if not value:
        return []

    if isinstance(value, list):
        return value

    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError:
            return [value]
        return parsed if isinstance(parsed, list) else [parsed]

    return [value]


def course_from_legacy_item(Course, University, item, default_university_code):
    if isinstance(item, dict):
        university = item.get("university") or item.get("university_code") or default_university_code
        prefix = item.get("prefix") or item.get("course_prefix")
        number = item.get("number") or item.get("course_number")
        code = item.get("course") or item.get("course_code") or item.get("course_key")

        if prefix and number:
            return get_or_create_course(Course, University, university, prefix, number)

        if code:
            return course_from_legacy_item(Course, University, code, university)

        return None

    raw_value = str(item or "").strip()
    if not raw_value:
        return None

    if ":" in raw_value:
        university, course_code = raw_value.split(":", 1)
    else:
        university = default_university_code
        course_code = raw_value

    prefix, number = split_course_code(course_code)
    return get_or_create_course(Course, University, university, prefix, number)


def forwards(apps, schema_editor):
    University = apps.get_model("api", "University")
    Course = apps.get_model("api", "Course")
    User = apps.get_model("api", "User")
    TutorProfile = apps.get_model("api", "TutorProfile")
    SessionRequest = apps.get_model("api", "SessionRequest")

    for code, name in COMMON_UNIVERSITIES.items():
        get_or_create_university(University, code, name)

    for user in User.objects.all().iterator():
        legacy_university = getattr(user, "university_name", "")
        university = get_or_create_university(University, legacy_university)
        user.university = university
        user.save(update_fields=["university"])

    for session_request in SessionRequest.objects.all().iterator():
        course = get_or_create_course(
            Course,
            University,
            getattr(session_request, "legacy_university", ""),
            getattr(session_request, "legacy_course_prefix", ""),
            getattr(session_request, "legacy_course_number", ""),
        )
        session_request.course = course
        session_request.save(update_fields=["course"])

    for tutor_profile in TutorProfile.objects.select_related("user__university").iterator():
        default_university_code = "UNKNOWN"
        if tutor_profile.user_id and tutor_profile.user.university_id:
            default_university_code = tutor_profile.user.university.code

        for item in parse_legacy_courses(getattr(tutor_profile, "legacy_courses_can_teach", [])):
            course = course_from_legacy_item(Course, University, item, default_university_code)
            if course:
                tutor_profile.courses_can_teach.add(course)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prefix", models.CharField(max_length=10)),
                ("number", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("university", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="courses", to="api.university")),
            ],
            options={
                "ordering": ["university__code", "prefix", "number"],
                "constraints": [
                    models.UniqueConstraint(fields=("university", "prefix", "number"), name="unique_course_per_university")
                ],
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="university",
            new_name="university_name",
        ),
        migrations.AddField(
            model_name="user",
            name="university",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="users", to="api.university"),
        ),
        migrations.RenameField(
            model_name="tutorprofile",
            old_name="courses_can_teach",
            new_name="legacy_courses_can_teach",
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="courses_can_teach",
            field=models.ManyToManyField(blank=True, related_name="tutor_profiles", to="api.course"),
        ),
        migrations.RenameField(
            model_name="sessionrequest",
            old_name="university",
            new_name="legacy_university",
        ),
        migrations.RenameField(
            model_name="sessionrequest",
            old_name="course_prefix",
            new_name="legacy_course_prefix",
        ),
        migrations.RenameField(
            model_name="sessionrequest",
            old_name="course_number",
            new_name="legacy_course_number",
        ),
        migrations.RenameField(
            model_name="sessionrequest",
            old_name="course_key",
            new_name="legacy_course_key",
        ),
        migrations.AddField(
            model_name="sessionrequest",
            name="course",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="session_requests", to="api.course"),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="university",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="users", to="api.university"),
        ),
        migrations.AlterField(
            model_name="sessionrequest",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="session_requests", to="api.course"),
        ),
        migrations.RemoveField(
            model_name="user",
            name="university_name",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="legacy_courses_can_teach",
        ),
        migrations.RemoveField(
            model_name="sessionrequest",
            name="legacy_university",
        ),
        migrations.RemoveField(
            model_name="sessionrequest",
            name="legacy_course_prefix",
        ),
        migrations.RemoveField(
            model_name="sessionrequest",
            name="legacy_course_number",
        ),
        migrations.RemoveField(
            model_name="sessionrequest",
            name="legacy_course_key",
        ),
    ]
