# Generated by Django 6.0.3 on 2026-06-14 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tutorprofile_status_last_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('in_person', 'In Person')], default='remote', max_length=20),
        ),
        migrations.CreateModel(
            name='SessionRequestOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.sessionrequest')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to='api.tutorprofile')),
            ],
            options={
                'ordering': ['offered_at'],
                'constraints': [models.UniqueConstraint(fields=('request', 'tutor'), name='unique_offer_per_tutor_per_request')],
            },
        ),
    ]
