# Generated by Django 6.0.3 on 2026-07-08 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_sessionrequest_mode_sessionrequestoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('tutor_no_show', 'Tutor did not show up'), ('student_no_show', 'Student did not show up'), ('poor_quality', 'Session quality was poor'), ('technical_issue', 'Technical issues prevented the session'), ('payment_dispute', 'Dispute over payment amount'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.tutoringsession')),
            ],
        ),
    ]
