# Generated by Django 6.0.3 on 2026-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sessionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='accumulated_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutoringsession',
            name='billing_resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringsession',
            name='student_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringsession',
            name='tutor_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
