from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    RegisterView,
    LoginView,
    ProfileView,
    UniversityListView,
    CourseListView,
    TutorProfileView,
    SessionRequestView,
    TutoringSessionListView,
    CreateTutoringSessionView,
    TutoringSessionDetailView,
    PaymentListView,
    PaymentCreateView,
    PaymentDetailView,
    PaymentUpdateView,
    ReviewListView,
    ReviewCreateView,
    ReviewDetailView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('universities/', UniversityListView.as_view(), name='universities'),
    path('courses/', CourseListView.as_view(), name='courses'),
    path('tutor-profile/', TutorProfileView.as_view(), name='tutor_profile'),
    path('session-requests/', SessionRequestView.as_view(), name='session_requests'),
    path('sessions/', TutoringSessionListView.as_view(), name='tutoring_sessions'),
    path('sessions/create/', CreateTutoringSessionView.as_view(), name='create_tutoring_session'),
    path('sessions/<int:session_id>/', TutoringSessionDetailView.as_view(), name='tutoring_session_detail'),
    path("payments/", PaymentListView.as_view(), name="payments-list"),
    path("payments/create/", PaymentCreateView.as_view(), name="payments-create"),
    path("payments/<int:payment_id>/", PaymentDetailView.as_view(), name="payments-detail"),
    path("payments/<int:payment_id>/update/", PaymentUpdateView.as_view(), name="payments-update"),
    path("reviews/", ReviewListView.as_view(), name="reviews-list"),
    path("reviews/create/", ReviewCreateView.as_view(), name="reviews-create"),
    path("reviews/<int:review_id>/", ReviewDetailView.as_view(), name="reviews-detail"),
]